import pickle
import numpy as np
import json
import sys
import os
import logging
import random
import re
from util import load_config, setup_logging

def bytes_to_bits(bytes_data, n):
    """
    Convert bytes (little-endian dump of uint64 array) to list of bits.
    Assumes the bytes were generated by bytes(ctypes_array) on a little-endian system.
    """
    bits = []
    for byte in bytes_data:
        for i in range(8):
            bits.append((byte >> i) & 1)
            if len(bits) >= n:
                return np.array(bits, dtype=int)
    return np.array(bits, dtype=int)

class NumpyCompatUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module == 'numpy._core.multiarray':
            module = 'numpy.core.multiarray'
        elif module == 'numpy._core.numeric':
            module = 'numpy._core.numeric'
        elif module == 'numpy._core.umath':
            module = 'numpy.core.umath'
        elif module == 'numpy._core':
            module = 'numpy.core'
        return super().find_class(module, name)

def load_record(filename):
    """
    Load simulation oracle output from pickle file.
    """
    with open(filename, 'rb') as f:
        return NumpyCompatUnpickler(f).load()

def process_key_record(key_record, templates, num_vec, n, n1, n2, mode="test", output_file=""):
    """
    Process a single key record to calculate stats (number of errors/ones in the first n positions in the reordered key vector).
    """
    # 1. Extract and convert key bits
    x_bytes = key_record['x']
    y_bytes = key_record['y']
    
    x_bits = bytes_to_bits(x_bytes, n)
    y_bits = bytes_to_bits(y_bytes, n)
    
    # Truncate to n1*n2
    x_bits = x_bits[:n1 * n2]
    y_bits = y_bits[:n1 * n2]
    
    # 2. Calculate LLRs (Log-Likelihood Ratios)
    # LLR = log(P(0) / P(1)) = log((1 - P(1)) / P(1))
    # Initialize LLR arrays (all 0s)
    x_llrs = np.zeros(len(x_bits), dtype=float)
    y_llrs = np.zeros(len(y_bits), dtype=float)
    
    # Iterate through the "ct details" which contains results for each error pattern
    ct_details = key_record['ct details']
    # only use the first num_vec ct details
    if len(ct_details) < num_vec:
        logging.warning(f"Requested {num_vec} patterns but record only has {len(ct_details)}. Using {len(ct_details)}.")
    ct_details = ct_details[:num_vec]
            
    for idx, detail in enumerate(ct_details): # the first ct corresponds to the first error pattern/template
        if mode == "test": # Get simulated oracle outputs for this pattern
            # m_x and m_y are lists of 0/1 from the perfect decoding
            m_x = list(detail['binary_m_x']) 
            m_y = list(detail['binary_m_y'])
            
            # Apply bit flip with probability 1 - rho
            rho=0.7
            for i in range(len(m_x)):
                if random.random() > rho:
                    m_x[i] = 1 - m_x[i]
            
            for i in range(len(m_y)):
                if random.random() > rho:
                    m_y[i] = 1 - m_y[i]
            
        elif mode == "experiment": # get oracle outputs from FPGA (?). not implemented here
            predicted_list = np.load(output_file)
            m_x = np.array(predicted_list[idx*2], dtype=int)
            m_y = np.array(predicted_list[idx*2+1], dtype=int)

        # use the template for this error pattern
        pat_idx = detail['error_pattern_idx']
        this_template = templates[pat_idx]['template']
        
        # Apply to x part
        # m_x has length n1 (number of blocks)
        for block_idx, val in enumerate(m_x):
            # Get probability vector for this outcome (0 or 1)
            # This is P(1)
            prob_vec = np.array(this_template[str(val)])
            
            # Clip probabilities to avoid log(0)
            prob_vec = np.clip(prob_vec, 1e-12, 1.0 - 1e-12)
            
            # Calculate LLR: log(P(0)/P(1)) = log((1-p)/p)
            llr_vec = np.log((1.0 - prob_vec) / prob_vec)
            
            # Add to the corresponding slice of x_llrs
            start = block_idx * n2
            end = start + n2
            x_llrs[start:end] += llr_vec

        # Apply to y part
        for block_idx, val in enumerate(m_y):
            prob_vec = np.array(this_template[str(val)])
            prob_vec = np.clip(prob_vec, 1e-12, 1.0 - 1e-12)
            llr_vec = np.log((1.0 - prob_vec) / prob_vec)
            
            start = block_idx * n2
            end = start + n2
            y_llrs[start:end] += llr_vec

    # 3. Combine x and y parts
    xy_bits = np.concatenate((x_bits, y_bits))
    xy_llrs = np.concatenate((x_llrs, y_llrs))
    
    # Sort by LLR descending
    # We want to count errors (1s) in the "most likely to be 0" positions
    sorted_indices = np.argsort(-xy_llrs)
    sorted_xy = xy_bits[sorted_indices]
    sorted_xy_llrs = xy_llrs[sorted_indices]
    
    # 5. Count errors in first n positions
    errors = np.sum(sorted_xy[:n])
    
    return errors, sorted_xy, sorted_xy_llrs

def main(scheme, num_vec, mode='test'):
    # Load parameters
    params = load_config(scheme)
    n = params.get("n", 17669)
    n1 = params.get("n1", 46)
    n2 = params.get("n2", 384)
    
    setup_logging(script="new_cal_stats_oracle", scheme=scheme)
    logging.info(f"Calculating stats for {scheme} with {num_vec} error patterns. Mode: {mode}.")
    
    # Load templates
    template_path = f'./templates/{scheme}_80_rho0.7.json'
    logging.info(f"Loading templates from {template_path}")
    with open(template_path, 'r') as f:
        templates = json.load(f)
    # Slice templates to match num_vec
    if len(templates) < num_vec:
        logging.warning(f"Requested {num_vec} patterns but found only {len(templates)} templates.")
    templates = templates[:num_vec]
    
    # Load simulation oracle output (pickle files)
    files = [] # Initialize files to an empty list
    if mode == 'test':
        output_dir = "./my_output/ct"
        files = [f for f in os.listdir(output_dir) if f.startswith(f"{scheme}_decap_ct_key") and f.endswith(".pkl")]
        logging.info(f"Found {len(files)} pickle files in the form of {scheme}_decap_ct_key*.pkl.")

    elif mode == 'experiment': # not implemented here
        #logging.info("Loading oracle outputs from FPGA.")
        output_dir = "./my_output_2/ct"
        files = [f for f in os.listdir(output_dir) if f.startswith(f"{scheme}_decap_ct_key") and f.endswith(".pkl")]
        logging.info(f"Found {len(files)} pickle files in the form of {scheme}_decap_ct_key*.pkl.")

    
    stats = [] # process each key and collect number of errors in the first n positions in the reordered key vector
    all_results = []
    
    model_folder = "../ourModels/test/"
    logging.info(f"Using models from {model_folder}.")

    for filename in files:
        filepath = os.path.join(output_dir, filename)
        
        # Extract key index from filename
        match = re.search(r'key(\d+)\.pkl', filename)
        key_idx = match.group(1) if match else "unknown"
        
        logging.info(f"Processing key {key_idx} ({filepath})")
        
        try:
            key_record = load_record(filepath)
            output_file = model_folder + "predicted-test-"+str(key_idx)+".npy"
            errors, sorted_xy, sorted_xy_llrs = process_key_record(key_record, templates, num_vec, n, n1, n2, mode=mode, output_file=output_file)
            stats.append(errors)
            logging.info(f"Key {key_idx}: {errors} errors in top {n} positions")
            
            # Collect detailed results
            result_entry = {
                'key_idx': key_idx,
                'h': key_record.get('h'),
                's': key_record.get('s'),
                'sorted_xy': sorted_xy,
                'sorted_xy_llrs': sorted_xy_llrs
            }
            all_results.append(result_entry)
            
        except Exception as e:
            print(f"Failed to process {filename}: {e}")
            import traceback
            traceback.print_exc()

    if stats:
        avg_errors = np.mean(stats)
        logging.info(f"Average number of errors: {avg_errors}")
    else:
        print("No valid records processed.")
        logging.info("No valid records processed.")

    
        
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python src/cal_stats_using_oracle_output.py <number of error patterns used> [mode: test or experiment]")
        sys.exit(1)
    
    scheme = 'hqc128'
    num_vec = int(sys.argv[1])
    
    if len(sys.argv) >= 3:
        mode = sys.argv[2]
    else:
        mode = 'test'
    
    main(scheme, num_vec, mode)
